### ISSUE TITLE
Add more buttons? Snes Advantage?

### ISSUE THREAD

**Issue by shantigilbert** [bbtinkerer/NesClassicAdvantage#1]
As far as I can tell with my limited knowledge it seems you are wiring the buttons directly to the Atmega, as opposed to the original Wii retropad adapter. But does this mean we could not add more buttons? say to make an SNES advantage?

**Comment by bbtinkerer** [comment]
You can either use IO port expander or use the analog channels to do buttons but they will require extra hardware and more coding. You could also use an AVR chip with more IO ports such as ATmega32A which has 32 IO ports; I think that could do without extra hardware for your SNES buttons. I chose the ATmega328P because that's what was on the Arduino when I first started trying out the retropad adapter code. Just happens that the chip has enough ports for what I need.
